export interface City {
  slug: string;
  name: string;
  state: string;
  zip: string;
  lat: number;
  lng: number;
  highway: string;
  neighborhoods: string;
  angle: string;
  population: string;
  profile: string;
}

export const CITIES: City[] = [
  {
    slug: 'frisco-tx',
    name: 'Frisco',
    state: 'TX',
    zip: '75034',
    lat: 33.1507,
    lng: -96.8236,
    highway: 'Sam Rayburn Tollway (SH-121)',
    neighborhoods: 'Starwood, Stonebriar, Chapel Creek',
    angle: 'luxury vehicle specialists',
    population: '200,000+',
    profile: 'high-income community with significant luxury and newer vehicle concentration',
  },
  {
    slug: 'mckinney-tx',
    name: 'McKinney',
    state: 'TX',
    zip: '75070',
    lat: 33.1972,
    lng: -96.6397,
    highway: 'US-75 (Central Expressway)',
    neighborhoods: 'Craig Ranch, Stonebridge Ranch, Eldorado, Tucker Hill',
    angle: 'concierge service for master-planned community residents',
    population: '230,000+',
    profile: 'one of the fastest-growing cities in Texas with high concentration of newer vehicles and leased cars',
  },
  {
    slug: 'plano-tx',
    name: 'Plano',
    state: 'TX',
    zip: '75024',
    lat: 33.0198,
    lng: -96.6989,
    highway: 'Dallas North Tollway',
    neighborhoods: 'Willow Bend, Legacy West, Jack Carter',
    angle: 'State Farm claim specialists — we know the process cold',
    population: '290,000+',
    profile: 'home to State Farm regional HQ and many tech corridor workers with newer vehicles',
  },
  {
    slug: 'allen-tx',
    name: 'Allen',
    state: 'TX',
    zip: '75013',
    lat: 33.1032,
    lng: -96.6705,
    highway: 'US-75',
    neighborhoods: 'Twin Creeks, Watters Creek, Bethany Road, Bray Central',
    angle: 'trusted by Allen families with newer vehicles',
    population: '110,000+',
    profile: 'highly rated school district drives affluent family concentration with newer vehicles',
  },
  {
    slug: 'prosper-tx',
    name: 'Prosper',
    state: 'TX',
    zip: '75078',
    lat: 33.2362,
    lng: -96.8003,
    highway: 'Preston Road (CR-2478)',
    neighborhoods: 'Windsong Ranch, Star Trail, Whitley Place',
    angle: "white-glove service for Prosper's luxury vehicles — we come to you",
    population: '45,000+',
    profile: 'median household income $187K, average home value $823K — one of the wealthiest suburbs in America with newest vehicles in DFW',
  },
  {
    slug: 'celina-tx',
    name: 'Celina',
    state: 'TX',
    zip: '75009',
    lat: 33.3237,
    lng: -96.7856,
    highway: 'US-380 (University Drive)',
    neighborhoods: 'Light Farms, Lariat, Mustang Lakes',
    angle: 'new to Texas hail? We guide you through every step',
    population: '60,000+',
    profile: '#1 fastest-growing city in America — most residents recently relocated and are experiencing Texas hail for the first time with brand new vehicles',
  },
  {
    slug: 'the-colony-tx',
    name: 'The Colony',
    state: 'TX',
    zip: '75056',
    lat: 33.0851,
    lng: -96.8883,
    highway: 'SH-121 (Sam Rayburn Tollway)',
    neighborhoods: 'Grandscape area, Stewart Creek',
    angle: 'convenient mobile service near Grandscape',
    population: '50,000+',
    profile: 'growing community with young families and newer vehicles, convenient access off SH-121',
  },
  {
    slug: 'little-elm-tx',
    name: 'Little Elm',
    state: 'TX',
    zip: '75068',
    lat: 33.1629,
    lng: -96.9369,
    highway: 'FM-720',
    neighborhoods: 'Paloma Creek, The Shores, Sunset Pointe',
    angle: 'fast response after Lake Lewisville area storms',
    population: '60,000+',
    profile: 'lakefront community hit hard by March 2024 hail event — residents are familiar with hail damage and want fast, quality repair',
  },
  {
    slug: 'aubrey-tx',
    name: 'Aubrey',
    state: 'TX',
    zip: '76227',
    lat: 33.3029,
    lng: -96.9839,
    highway: 'US-380',
    neighborhoods: 'Arrow Brooke, Sandbrock Ranch',
    angle: 'mobile PDR service that comes to you in Aubrey',
    population: '12,000+',
    profile: 'fast-growing newer community north of Denton with newer vehicles and residents who need mobile PDR service',
  },
  {
    slug: 'richardson-tx',
    name: 'Richardson',
    state: 'TX',
    zip: '75080',
    lat: 32.9482,
    lng: -96.7298,
    highway: 'US-75 (Central Expressway)',
    neighborhoods: 'Arapaho Corridor, CityLine, Breckinridge Park',
    angle: 'State Farm HQ city — nobody knows the claim process better',
    population: '120,000+',
    profile: 'home to State Farm corporate campus and major tech employers including Samsung — many residents have State Farm coverage and work in tech',
  },
  {
    slug: 'garland-tx',
    name: 'Garland',
    state: 'TX',
    zip: '75040',
    lat: 32.9126,
    lng: -96.6389,
    highway: 'I-635 (LBJ Freeway)',
    neighborhoods: 'Firewheel area, Sachse border',
    angle: 'fast quality repairs for Garland families',
    population: '245,000+',
    profile: 'large dense community with a wide range of vehicles and budget-conscious but quality-seeking customers',
  },
  {
    slug: 'carrollton-tx',
    name: 'Carrollton',
    state: 'TX',
    zip: '75006',
    lat: 32.9537,
    lng: -96.8903,
    highway: 'I-35E',
    neighborhoods: 'Josey Ranch, Keller Springs',
    angle: 'quick turnaround for North Dallas commuters',
    population: '140,000+',
    profile: 'diverse community of commuters and families with newer vehicles along the I-35E corridor',
  },
  {
    slug: 'addison-tx',
    name: 'Addison',
    state: 'TX',
    zip: '75001',
    lat: 32.9612,
    lng: -96.8311,
    highway: 'Dallas North Tollway',
    neighborhoods: 'Addison Circle, Village on the Parkway area',
    angle: "premium service for Addison's upscale community",
    population: '16,000+',
    profile: 'small affluent community known for restaurants and upscale lifestyle — residents expect premium service and have luxury vehicles',
  },
  {
    slug: 'denton-tx',
    name: 'Denton',
    state: 'TX',
    zip: '76201',
    lat: 33.2148,
    lng: -97.1331,
    highway: 'I-35E',
    neighborhoods: 'Robson Ranch, Lantana, near UNT/TWU',
    angle: 'serving Denton families, students, and professionals',
    population: '145,000+',
    profile: 'college town (UNT, TWU) with mix of students, young professionals, and established families — wide range of vehicle types',
  },
  {
    slug: 'southlake-tx',
    name: 'Southlake',
    state: 'TX',
    zip: '76092',
    lat: 32.9401,
    lng: -97.1336,
    highway: 'SH-114',
    neighborhoods: 'Timarron, Carillon, Southridge Lakes',
    angle: "ultra-luxury vehicle care for Southlake's premium community",
    population: '32,000+',
    profile: 'one of the highest-income communities in Texas — Porsche, Range Rover, Ferrari ownership is common; residents demand white-glove service and flawless results',
  },
  {
    slug: 'wylie-tx',
    name: 'Wylie',
    state: 'TX',
    zip: '75098',
    lat: 33.0151,
    lng: -96.5388,
    highway: 'SH-78',
    neighborhoods: 'Woodbridge, Bozman Farms, Kreymer Estates',
    angle: 'fast-growing East Collin County community with newer vehicles',
    population: '65,000+',
    profile: 'rapidly growing suburb east of McKinney with a high concentration of newer homes and newer vehicles',
  },
  {
    slug: 'sachse-tx',
    name: 'Sachse',
    state: 'TX',
    zip: '75048',
    lat: 32.9765,
    lng: -96.5891,
    highway: 'SH-78',
    neighborhoods: 'Creek Hollow, Maxwell Creek, Sachse Town Center',
    angle: 'convenient PDR service between Garland and Wylie',
    population: '30,000+',
    profile: 'suburban community between Garland and Wylie with working families and newer vehicles',
  },
  {
    slug: 'murphy-tx',
    name: 'Murphy',
    state: 'TX',
    zip: '75094',
    lat: 33.0151,
    lng: -96.6116,
    highway: 'FM-544',
    neighborhoods: 'Maxwell Creek North, Sonoma Verde, Heritage Park',
    angle: 'trusted by Murphy families between Allen and Wylie',
    population: '22,000+',
    profile: 'upscale small suburb between Allen and Wylie known for top-rated schools and higher-income families with newer vehicles',
  },
  {
    slug: 'rowlett-tx',
    name: 'Rowlett',
    state: 'TX',
    zip: '75088',
    lat: 32.9029,
    lng: -96.5636,
    highway: 'I-30 / SH-66',
    neighborhoods: 'Waterview, Schrade Road area, Lake Ray Hubbard corridor',
    angle: 'lakeside community — fast repair before the next storm season',
    population: '70,000+',
    profile: 'Lake Ray Hubbard community with a mix of established and newer homes; hit by 2024-2025 DFW hail events',
  },
  {
    slug: 'rockwall-tx',
    name: 'Rockwall',
    state: 'TX',
    zip: '75032',
    lat: 32.9318,
    lng: -96.4597,
    highway: 'I-30',
    neighborhoods: 'Heath, Ridge Road area, Lakefront communities',
    angle: 'Rockwall and Heath area luxury vehicle specialists',
    population: '55,000+',
    profile: 'affluent Lake Ray Hubbard community; Rockwall and neighboring Heath were among the hardest-hit areas in the 2025 historic DFW storm',
  },
  {
    slug: 'lewisville-tx',
    name: 'Lewisville',
    state: 'TX',
    zip: '75067',
    lat: 33.0462,
    lng: -96.9942,
    highway: 'I-35E',
    neighborhoods: 'Castle Hills, Coppell border, Vista Ridge area',
    angle: 'serving Lewisville and Lake Lewisville area drivers',
    population: '115,000+',
    profile: 'large growing community near Lake Lewisville; Castle Hills area has high-end newer vehicles; diverse vehicle mix across the city',
  },
  {
    slug: 'flower-mound-tx',
    name: 'Flower Mound',
    state: 'TX',
    zip: '75028',
    lat: 33.0146,
    lng: -97.0969,
    highway: 'FM-2499 / SH-121',
    neighborhoods: 'Bridlewood, Canyon Falls, Wellington',
    angle: "premium service for Flower Mound's master-planned communities",
    population: '85,000+',
    profile: 'consistently ranked among best places to live in Texas; high household income, newer luxury vehicles, and master-planned communities expecting premium service',
  },
  {
    slug: 'coppell-tx',
    name: 'Coppell',
    state: 'TX',
    zip: '75019',
    lat: 32.9543,
    lng: -97.0149,
    highway: 'SH-121 / Belt Line Road',
    neighborhoods: 'Old Town Coppell, Coppell Town Center, near DFW Airport',
    angle: "white-glove service for Coppell's high-income community",
    population: '42,000+',
    profile: 'one of the highest-income cities in DFW; near DFW Airport; Coppell residents expect premium service and drive newer luxury vehicles',
  },
  {
    slug: 'grapevine-tx',
    name: 'Grapevine',
    state: 'TX',
    zip: '76051',
    lat: 32.9343,
    lng: -97.0781,
    highway: 'SH-114 / SH-121',
    neighborhoods: 'Historic Downtown Grapevine, Stone Bridge Estates, Silverlake',
    angle: 'trusted by Grapevine and DFW Airport corridor drivers',
    population: '55,000+',
    profile: 'historic city near DFW Airport with corporate travelers, frequent flyers, and a mix of established and luxury vehicles',
  },
  {
    slug: 'colleyville-tx',
    name: 'Colleyville',
    state: 'TX',
    zip: '76034',
    lat: 32.8887,
    lng: -97.1503,
    highway: 'SH-26 / Glade Road',
    neighborhoods: 'Woodland Hills, La Paloma, Bransford Estates',
    angle: "ultra-luxury service for one of DFW's most affluent communities",
    population: '28,000+',
    profile: 'one of the wealthiest cities in Texas; median household income over $175K; residents drive high-end European vehicles and expect flawless, white-glove service',
  },
  {
    slug: 'irving-tx',
    name: 'Irving',
    state: 'TX',
    zip: '75038',
    lat: 32.8140,
    lng: -96.9489,
    highway: 'SH-183 / Loop 12',
    neighborhoods: 'Las Colinas, Valley Ranch, Heritage District',
    angle: 'serving Irving and Las Colinas business district drivers',
    population: '250,000+',
    profile: 'major corporate hub (Las Colinas) with a large population of business professionals, company vehicles, and newer personal cars',
  },
  {
    slug: 'mesquite-tx',
    name: 'Mesquite',
    state: 'TX',
    zip: '75150',
    lat: 32.7668,
    lng: -96.5992,
    highway: 'I-635 / US-80',
    neighborhoods: 'Sunridge Park, Buckner Terrace, Lawson Farms',
    angle: 'fast, affordable repairs for Mesquite families',
    population: '145,000+',
    profile: 'large east Dallas suburb with a broad mix of working and middle-class families; strong demand for quality repairs at fair prices',
  },
  {
    slug: 'anna-tx',
    name: 'Anna',
    state: 'TX',
    zip: '75409',
    lat: 33.3487,
    lng: -96.5472,
    highway: 'US-75 (Central Expressway)',
    neighborhoods: 'Avery Pointe, Hurricane Creek, Anna Town Square',
    angle: 'growing North Collin County community — we come to you',
    population: '25,000+',
    profile: 'fast-growing suburb north of McKinney; newer community with newer vehicles; residents appreciate mobile service that avoids long drives to the city',
  },
  {
    slug: 'forney-tx',
    name: 'Forney',
    state: 'TX',
    zip: '75126',
    lat: 32.7479,
    lng: -96.4710,
    highway: 'US-80',
    neighborhoods: 'Travis Ranch, Clements Ranch, Gateway Parks',
    angle: "Kaufman County's fast-growing community — mobile PDR service",
    population: '35,000+',
    profile: 'one of the fastest-growing suburbs east of Dallas; new construction communities with newer vehicles; commuters to Dallas prefer mobile PDR service',
  },
  {
    slug: 'pilot-point-tx',
    name: 'Pilot Point',
    state: 'TX',
    zip: '76258',
    lat: 33.3954,
    lng: -96.9608,
    highway: 'US-377',
    neighborhoods: 'Historic downtown, rural and ranch properties',
    angle: 'mobile PDR serving Pilot Point and the rural North Texas corridor',
    population: '6,000+',
    profile: 'small community northwest of Aubrey; rural and ranch properties with newer trucks and SUVs; mobile service is essential here',
  },
  {
    slug: 'gunter-tx',
    name: 'Gunter',
    state: 'TX',
    zip: '75058',
    lat: 33.4432,
    lng: -96.7413,
    highway: 'US-75 (Central Expressway)',
    neighborhoods: 'Gunter ISD area, new developments along US-75',
    angle: 'North Collin County mobile PDR — we come to you',
    population: '5,000+',
    profile: 'small but growing community on the northern edge of Collin County; newer residents relocating from Frisco/McKinney corridor with newer vehicles',
  },
  {
    slug: 'highland-village-tx',
    name: 'Highland Village',
    state: 'TX',
    zip: '75077',
    lat: 33.0915,
    lng: -97.0561,
    highway: 'FM-2499',
    neighborhoods: 'Doubletree Ranch, The Cove, Lakeland Hills',
    angle: "premium service for Highland Village's lakefront community",
    population: '18,000+',
    profile: 'affluent lakefront community between Lewisville and Flower Mound; high-income residents with newer luxury vehicles who expect premium results',
  },
  {
    slug: 'lantana-tx',
    name: 'Lantana',
    state: 'TX',
    zip: '76226',
    lat: 33.0826,
    lng: -97.1415,
    highway: 'FM-407',
    neighborhoods: 'Lantana Golf Club area, Trophy Club border',
    angle: 'master-planned community luxury service — Lantana and Trophy Club',
    population: '12,000+',
    profile: 'upscale master-planned community near Argyle; young affluent families with newer luxury vehicles; covers Trophy Club border area',
  },
  {
    slug: 'trophy-club-tx',
    name: 'Trophy Club',
    state: 'TX',
    zip: '76262',
    lat: 32.9995,
    lng: -97.1763,
    highway: 'SH-114',
    neighborhoods: "Trophy Club Country Club, Hogan's Glen, Turnberry",
    angle: "premium PDR for Trophy Club's golf community",
    population: '15,000+',
    profile: 'golf and country club community near Westlake; high-income residents with luxury and exotic vehicles; neighbor to Southlake and Colleyville demographics',
  },
  {
    slug: 'mansfield-tx',
    name: 'Mansfield',
    state: 'TX',
    zip: '76063',
    lat: 32.5632,
    lng: -97.1413,
    highway: 'US-287',
    neighborhoods: 'South Pointe, Walnut Creek, Heritage',
    angle: 'serving South DFW families in Mansfield and Tarrant County',
    population: '80,000+',
    profile: 'growing south Tarrant County suburb with a mix of working and middle-class families; strong demand for affordable quality hail repair',
  },
];

export function getCityBySlug(slug: string): City | undefined {
  return CITIES.find((c) => c.slug === slug);
}

export function getNearbyCities(slug: string, count = 4): City[] {
  const city = getCityBySlug(slug);
  if (!city) return [];
  return CITIES.filter((c) => c.slug !== slug)
    .sort((a, b) => {
      const distA = Math.sqrt(Math.pow(a.lat - city.lat, 2) + Math.pow(a.lng - city.lng, 2));
      const distB = Math.sqrt(Math.pow(b.lat - city.lat, 2) + Math.pow(b.lng - city.lng, 2));
      return distA - distB;
    })
    .slice(0, count);
}
